---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: capstone
  region: us-east-2
  version: '1.18'
iam:
  withOIDC: true 
managedNodeGroups:
- name: <ng-linux>
  launchTemplate:
    id: lt-<id>
    version: "<1>"